CI: Promotion fix test & PR template updated

diff --git a/.github/workflows/promotion.yml b/.github/workflows/promotion.yml
--- a/.github/workflows/promotion.yml
+++ b/.github/workflows/promotion.yml
@@ -30,15 +30,26 @@ jobs:
 
     - name: Promote artifact
       run: |
-        VERSION="${{ steps.version.outputs.version }}"
-        BUILD_NAME="${{ github.event.repository.name }}"  
-        
-        BUILD_NUMBER="$(jfrog rt curl api/build/${BUILD_NAME} -s | jq -e -r '[.buildsNumbers[] | select(.uri | contains("'$VERSION'"))] | sort_by(.started) | reverse | .[0].uri[1:]')"
+        VERSION="v1.0.4"
+        BUILD_NAME="${{ github.event.repository.name }}"
 
-        if [ -z "$BUILD_NUMBER" ]; then
-          echo "::error::Error retrieving build from Artifactory. No matching name/version. Name: $BUILD_NAME; Version: $VERSION"
-          exit 1
-        fi
+          BUILD_NUMBER=$(
+            jfrog rt curl api/build/${BUILD_NAME} -s | \
+            jq -r "
+              [
+                .buildsNumbers[]
+                | select(.uri | contains(\"$VERSION\"))
+              ]
+              | sort_by(.started)
+              | reverse
+              | .[0].uri[1:]
+            "
+          )
 
-        echo "Promoting generic"
-        jfrog rt build-promote  "$BUILD_NAME" "$BUILD_NUMBER" eng-generic-prod-local --status released --copy=true
+          if [ -z "$BUILD_NUMBER" ]; then
+            echo "::error::Error retrieving build from Artifactory. No matching name/version. Name: $BUILD_NAME; Version: $VERSION"
+            exit 1
+          fi
+
+          echo "Promoting generic $BUILD_NAME $BUILD_NUMBER"
+          jfrog rt build-promote  "$BUILD_NAME" "$BUILD_NUMBER" eng-generic-prod-local --status released --copy=true
